### ISSUE TITLE
Need a favicon

### ISSUE THREAD

**Issue by expl0r3r** [DrBATU/bhendi#5]
We a need some icons, starting with a favicon for this app would be good

**Comment by iamrajhans** [comment]
![screen shot 2015-06-20 at 11 02 13 am](https://cloud.githubusercontent.com/assets/10916899/8266183/8b7a2824-173c-11e5-93ee-73f48b9c1584.png)

**Comment by expl0r3r** [comment]
How about this?
[favicon.ico | uploaded via ZenHub](https://files.zenhub.io/55850762a5e87d7a13418a61)

**Comment by iamrajhans** [comment]
great..!!

**Comment by sauraedron** [comment]
i have one. or is it commited already ?

**Comment by expl0r3r** [comment]
Upload yours to the assets/images folder. Try both out. Keep the one you like.
